### ISSUE TITLE
poolsapi file with the function calls should take the base url for rest api as a call parameter

### ISSUE THREAD

**Issue by Schwartz10** [glifio/go-pools#104]
https://github.com/glifio/go-pools/blob/protocol-v2/econ/glifapi.go these methods should be able to fetch from any endpoint and not hardcode to the mainnet production rest api url

**Comment by jimpick** [comment]
Would it make sense to add it to `fevmExtern` and set it up when the SDK is initialized?

https://github.com/glifio/go-pools/blob/5824f8a9814be7ffe6876d159971afa02db81382/sdk/types.go#L17

**Comment by jimpick** [comment]
I guess that's what issue #103 is saying

**Comment by jimpick** [comment]
PR #105 has my initial attempt at this
