### ISSUE TITLE
Create a sampling version of the preview termination method

### ISSUE THREAD

**Issue by Schwartz10** [glifio/go-pools#44]
The idea here is to find how many samples of sectors you need to take in order to get a certain precision of accuracy compared to the precise method

**Comment by jimpick** [comment]
Here's the go-pool code for terminating sectors:

* https://github.com/glifio/go-pools/blob/jim/preview-terminate-sectors/sdk/preview_termination_queries.go

Here's the CLI code:

* https://github.com/glif-confidential/pools-cli/blob/jim/terminate-testing/cmd/miner_preview_terminate_sector.go
