### ISSUE TITLE
Add data to observable notebook

### ISSUE THREAD

**Issue by Schwartz10** [glifio/go-pools#48]
Graphs to add:

1. RBP + QAP mapped over time (we'd like to be able to see correlation between power and recovery rates)
2. Sector age (see correlation between sector age and recovery rates)
3. Expected daily rewards (see correlation between EDR and RR)

For computing EDR:
1. We get the expected block rewards https://github.com/glifio/go-pools/blob/cc908ff193da89238da96612ca5edf4f07e8343c/mstat/mstat.go#L199
2. We add 1/180 of the miner's vesting balance https://github.com/glifio/go-pools/blob/cc908ff193da89238da96612ca5edf4f07e8343c/mstat/mstat.go#L160
3. https://github.com/glifio/go-pools/blob/cc908ff193da89238da96612ca5edf4f07e8343c/mstat/mstat.go#L166

**Comment by jimpick** [comment]
These were added.
